### ISSUE TITLE
hyper-parameter settings on BDCI16-TSDAD2 dataset

### ISSUE THREAD

**Issue by zhuotest** [CPFLAME/LOCO#2]
Hi, thanks for sharing this code.

I'm interested in the BDCI dataset's detection result. Now I've got BDCI training images and annotations,  and your LOCO algorithm inspires me. I'd like to reveal your reported detection result in your paper, but find that you didn't mention these settings:

- anchor aspect ratios
- anchor scales
- RPN_min
Are they the default parameters as used in py-faster-rcnn? i.e. [0.5, 1, 2] for anchor aspect ratios, [8, 16, 32] for anchor scales? What about RPN_min for BDCI? Is it 16 pixels as in py-faster-rcnn or 5 pixels as in your TT100K experiments?

Also, I'm not quite sure, is that true that you set these parameters in BDCI detection dataset:
- iter_size = 1, instead of the default iter_size=2 (for VGG16)
-  MAX_SIZE=1000, and SCALES: [1000,] for training and single scale testing

What's more, there are exactly 10000 images for training with annotated bounding boxes in BDCI16-TSDAD2, and 4000 annotated images in BDCI16-TSDAD1. How could you do experiment on BDCI16-TSDAD2 with 13500 training images and 23000 testing images, as described in your paper?

Looking forward to your reply, thanks.

**Comment by zhuotest** [comment]
@CPFLAME

**Comment by CPFLAME** [comment]
@zhuotest  I'm glad this project could help. sorry for my late reply.
For question 1: All settings for BDCI are the default parameters as py-faster-rcnn  for the convenience of comparison.(Adjusting anchor scales and ratios might get better performance)
For question 2: (1) I set iter_size to 1, cause I think the number  of objects in an image is enough for detectors to learn In BDCI dataset. (2)  the SCALES is [1000]  and MAX_SIZE is 2200 to ensure the shorter side of the source image has been resized to 1000.
For question 3: As you mentioned, there are about 14000 annotated images in total for BDCI16-TSDAD. we used them for training,  and there are 23000 testing images (no annotations) for testing. We  submit the result of testing images to the web and it returns mAP. But it has been closed after the end of the competition.
You can also send me your WeChat number to Peng_C@bupt.edu.cn for fast reply. I prefer communicating by Chinese.
Hope this can help.

**Comment by CPFLAME** [comment]
@zhuotest  I'm glad this project could help. sorry for my late reply.

For question 1: All settings for BDCI are the default parameters as py-faster-rcnn for the convenience of comparison.(Adjusting anchor scales and ratios might get better performance)


For question 2: (1) I set iter_size to 1, cause I think the number of objects in an image is enough for detectors to learn In BDCI dataset. (2) the SCALES is [1000] and MAX_SIZE is 2200 to ensure the shorter side of the source image has been resized to 1000.


For question 3: As you mentioned, there are about 14000 annotated images in total for BDCI16-TSDAD. we used them for training, and there are 23000 testing images (no annotations) for testing. We submit the result of testing images to the web and it returns mAP. But it has been closed after the end of the competition.


You can also send me your WeChat number to Peng_C@bupt.edu.cn for fast reply. I prefer communicating by Chinese.
Hope this can help.

**Comment by zhuotest** [comment]
@CPFLAME  Thanks for your sincerely reply.
